### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by dschuermann** [NightWhistler/HtmlSpanner#2]
Hi Alex,

I forked your project under https://github.com/dschuermann/HtmlSpanner and made several changes to fit my needs. I think you will not like every change, so I did not make a pull request. I just want to inform you about my changes:
- restructured the project as an android library project (also compiles to a jar)
- implemented spannable for ordered and unordered lists
- changed handling of whitespaces to a simpler implementation (I had problems with whitespaces after links and some other issues with the previous implementation)
- Introduce an ugly workaround for jelly bean regression bug (http://code.google.com/p/android/issues/detail?id=35466). On jelly beans b-tags are displayed as italic (don't know if that is enough to prevent crashes on JB)
- I am not familiar with maven so the pom file is not right at the moment

**Comment by nagendraksrivastava** [comment]
I tried to use your library for my android app but it is not getting com.osbcp.cssparser:cssparser:1.5 source and ended up with error, is there any fix for this ?
