### ISSUE TITLE
[Request] Need Gradle support to import lib in android studio.

### ISSUE THREAD

**Issue by naushad-madakiya** [NightWhistler/HtmlSpanner#36]

**Comment by NightWhistler** [comment]
What do you mean exactly? There is a build.gradle file... what would be needed to import it as a lib?

**Comment by naushad-madakiya** [comment]
Is there any gradle dependency to import this project as library ?

**Comment by JORDAN1998** [comment]
Yes please add a gradle dependency I have no idea how to add this to my android studio app. Most libraries have something that looks like this 

compile 'com.melnykov:floatingactionbutton:1.3.0'

that allows you to add the library to gradle

**Comment by NightWhistler** [comment]
Hmm, I see what you mean... the short-term solution is to install the plugin to your local repo using

  `mvn install`

or

  `./gradlew install`

and then to add

  ```
repositories {
    mavenLocal()
  }
```

to your build.gradle.

You're right though that it would be much nice to publish the plugin to a public repo... except that I have no idea how to do that. If someone can tell me how to get it published, I'll be happy to do so.

**Comment by NightWhistler** [comment]
This is basically the same as #43
