### ISSUE TITLE
Please, could you tell me, how to add this lib to android studio?

### ISSUE THREAD

**Issue by willwach** [NightWhistler/HtmlSpanner#40]
compile 'net.nightwhistler.htmlspanner:htmlspanner:+' not working in gradle file

**Comment by NightWhistler** [comment]
From your new issue, I assume you got the library working... can this issue be closed?

**Comment by willwach** [comment]
Many thanks for your responses to my questions und for this fantastic lib.
Yes, I found a way to integrate.

**Comment by JimVanG** [comment]
So how did you integrate it via Gradle?
