### ISSUE TITLE
Failed to import the liberary

### ISSUE THREAD

**Issue by adelemam** [NightWhistler/HtmlSpanner#46]
I am using Android studio but still failed to import the library, 
I have review the multiple issue related to same issue but failed, 
Also i tried to use jitpack
but failed to add the dependency which supposed to be 
        compile 'com.github.User:Repo:Tag' ( didn;t get the Tag text? )

can you help please??

**Comment by adelemam** [comment]
any help here please??

**Comment by NightWhistler** [comment]
The easiest way right now is to build the library locally and add mavenLocal() to your project as a repo.

**Comment by adelemam** [comment]
thank you!
