### ISSUE TITLE
error: package com.osbcp.cssparser does not exist

### ISSUE THREAD

**Issue by monowar1993** [NightWhistler/HtmlSpanner#50]
I have downloaded the jar file and included it to my gradle, Everything is synced. But when run the project it gives me the "error: package com.osbcp.cssparser does not exist". What am i doing wrong? Please help me out.

**Comment by kolorszczak** [comment]
You have to find jar of old version of cssparser (in my case it was 1.4) and add it as a dependency to a HtmlSpanner dependency section. Dont forget to delete old version from gradle.
