### ISSUE TITLE
Doesn't work with HtmlCleaner 2.4

### ISSUE THREAD

**Issue by juniperpansy** [NightWhistler/HtmlSpanner#8]
Just thought you might want to add it to the documentation.

I kept getting blank output when trying to use HtmlSpanner with HtmlCleaner 2.4

Works perfect with HtmlCleaner 2.2 though

**Comment by fbvictorhugo** [comment]
@NightWhistler  any solution ? 

Doesn't work with HtmlCleaner 2.12, the text isn't  appear.

**Comment by phillipm** [comment]
@NightWhistler bump to check if you have intentions of ever addressing this.

It looks like @sdcr has a fork that is compatible with HtmlCleaner 2.4 and above: https://github.com/sdcr/HtmlSpanner (see commit https://github.com/sdcr/HtmlSpanner/commit/c01045c681deecaa5642c0d99276b6df302bd963)

**Comment by NightWhistler** [comment]
It wasn't really high on my priority list, but it looks like the fixes that sdcr made should be easy enough to port back. I'll see if he's willing to send me a pull request. Thanks for the heads-up!

**Comment by NightWhistler** [comment]
Got a pull-request and just merged it, which should fix this issue.
